# Generated by Django 5.0.6 on 2026-07-20 17:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_id', models.UUIDField(unique=True)),
                ('customer_id', models.UUIDField()),
                ('provider_id', models.UUIDField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, default='')),
                ('provider_response', models.TextField(blank=True, default='')),
                ('flagged', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider_id'], name='reviews_rev_provide_c5a3cd_idx')],
            },
        ),
    ]
