# Generated by Django 5.0.6 on 2026-07-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('bookings_created', models.IntegerField(default=0)),
                ('bookings_completed', models.IntegerField(default=0)),
                ('bookings_cancelled', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('new_reviews', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.UUIDField(unique=True)),
                ('total_bookings', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_reviews', models.IntegerField(default=0)),
            ],
        ),
    ]
